# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_matrix:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore bvm/bvm.csproj
    - name: Build
      run: dotnet build --no-restore bvm/bvm.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal bvm.unittests/bvm.unittests.csproj
    - name: Publish Aot
      run: dotnet publish -c Release bvm/bvm.csproj
